sudo: false
services:
  - docker

script:
  - docker build -t experimentalplatform/buildstep:$TRAVIS_BRANCH .
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push experimentalplatform/buildstep:$TRAVIS_BRANCH

